definitions:
  models.Job:
    properties:
      created_at:
        description: 创建时间
        type: string
      id:
        description: 主键
        type: integer
      name:
        description: 任务名称
        type: string
      result:
        description: 任务结果
        type: string
      updated_at:
        description: 更新时间
        type: string
    type: object
info:
  contact: {}
  description: 任务管理系统
  license: {}
  title: 任务管理 API
  version: "1.0"
paths:
  /v1/job:
    get:
      description: 获取所有任务
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.Job'
      summary: 获取所有任务
      tags:
      - v1/job
    post:
      consumes:
      - multipart/form-data
      description: 新建任务
      parameters:
      - description: 任务名称
        in: formData
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.Job'
      summary: 新建任务
      tags:
      - v1/job
  /v1/job/{id}:
    delete:
      description: 删除任务
      parameters:
      - description: 任务id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 删除任务
      tags:
      - v1/job
    get:
      description: 获取单个任务
      parameters:
      - description: 任务id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.Job'
      summary: 获取单个任务
      tags:
      - v1/job
    put:
      consumes:
      - multipart/form-data
      description: 更新任务
      parameters:
      - description: 任务id
        in: path
        name: id
        required: true
        type: integer
      - description: 任务结果
        in: formData
        name: result
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 更新任务
      tags:
      - v1/job
swagger: "2.0"
tags:
- description: 任务管理
  name: v1/job
